apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod-nginx-fromdocker
  namespace: calico-demo 
spec:
  containers:
  - name: ubt-nginx-pod
    image: windni/aks:ubt1804nginx80web
    command:
      - "sleep"
      - "infinity"
  restartPolicy: Always
